"""Agent Seer: Specification-Driven Synthetic Evaluation & Deterministic Linting for MCP Agents."""
from .clients import (
    BaseLLMClient,
    GeminiClient,
    GemmaClient,
    LLMAuthError,
    LLMClientError,
    LLMConnectionError,
    LLMModelNotFoundError,
    LLMRateLimitError,
    LLMResponse,
    LLMResponseFormatError,
    LLMTimeoutError,
    MockClient,
    ModelGardenGemmaClient,
    TokenUsage,
    VertexGeminiClient,
    create_client,
    get_client,
)
from .discovery import (
    McpDiscovery,
    discover_from_stdio,
    discover_tools_stdio,
    load_capabilities,
    load_registry,
    load_server_directory,
    load_tools_and_capabilities,
    merge_capabilities,
)
from .judge import (
    AgentSeerJudge,
    JudgeEngine,
    extract_json_payload,
    format_agent_calls,
    format_tool_specs,
    judge_coherence,
    judge_tc,
)
from .linter import (
    DeterministicCapabilityLinter,
    DeterministicLinter,
)
from .models import (
    CapabilityMatrix,
    CoherenceScores,
    EvaluationResult,
    LintError,
    LintResult,
    LintViolation,
    ServerSpec,
    Severity,
    ToolCall,
    ToolCallingScores,
    ToolDefinition,
    ToolParameter,
)
from .pipeline import (
    AgentWorkflowStep,
    ConversationTurn,
    GroundedMockCall,
    GroundedMockScenario,
    MultiTurnTranscript,
    Scenario,
    ScenarioCollection,
    SyntheticEvalPipeline,
    SyntheticHarness,
    SyntheticHarnessGenerator,
    ToolInterpretation,
)
from .prompts import (
    COHERENCE_JUDGE_PROMPT,
    STAGE1_TOOL_INTERPRETATION,
    STAGE2_BOUNDARY,
    STAGE2_COMPLEX,
    STAGE2_SIMPLE,
    STAGE3_MOCK_OUTPUT,
    STAGE4_MULTI_TURN,
    TC_JUDGE_PROMPT,
    build_stage1_prompt,
    build_stage2_prompt,
    build_stage3_prompt,
    build_stage4_prompt,
    build_tool_summary,
)
from .scoring import (
    aggregate_coherence,
    aggregate_tc,
    apply_cascading_penalty_collapse,
    compute_coherence_score,
    compute_tool_calling_score,
    norm3,
    norm10,
)
from .testing.assertions import (
    assert_valid_tool_calls,
    evaluate_transcript,
)

__version__ = "1.0.0"

__all__ = [
    # Models
    "ToolParameter",
    "ToolDefinition",
    "ToolCall",
    "LintViolation",
    "LintError",
    "LintResult",
    "ToolCallingScores",
    "CoherenceScores",
    "CapabilityMatrix",
    "ServerSpec",
    "EvaluationResult",
    "Severity",
    # Discovery
    "McpDiscovery",
    "discover_from_stdio",
    "discover_tools_stdio",
    "load_server_directory",
    "load_registry",
    "merge_capabilities",
    "load_capabilities",
    "load_tools_and_capabilities",
    # Linter
    "DeterministicLinter",
    "DeterministicCapabilityLinter",
    # Scoring
    "compute_tool_calling_score",
    "compute_coherence_score",
    "apply_cascading_penalty_collapse",
    "aggregate_tc",
    "aggregate_coherence",
    "norm10",
    "norm3",
    # Judge
    "JudgeEngine",
    "AgentSeerJudge",
    "judge_tc",
    "judge_coherence",
    "extract_json_payload",
    "format_tool_specs",
    "format_agent_calls",
    # Pipeline
    "SyntheticEvalPipeline",
    "SyntheticHarnessGenerator",
    "SyntheticHarness",
    "ToolInterpretation",
    "Scenario",
    "ScenarioCollection",
    "GroundedMockScenario",
    "GroundedMockCall",
    "AgentWorkflowStep",
    "ConversationTurn",
    "MultiTurnTranscript",
    # Prompts
    "STAGE1_TOOL_INTERPRETATION",
    "STAGE2_SIMPLE",
    "STAGE2_COMPLEX",
    "STAGE2_BOUNDARY",
    "STAGE3_MOCK_OUTPUT",
    "STAGE4_MULTI_TURN",
    "TC_JUDGE_PROMPT",
    "COHERENCE_JUDGE_PROMPT",
    "build_stage1_prompt",
    "build_stage2_prompt",
    "build_stage3_prompt",
    "build_stage4_prompt",
    "build_tool_summary",
    # Clients
    "BaseLLMClient",
    "VertexGeminiClient",
    "ModelGardenGemmaClient",
    "MockClient",
    "GeminiClient",
    "GemmaClient",
    "TokenUsage",
    "LLMResponse",
    "LLMClientError",
    "LLMAuthError",
    "LLMRateLimitError",
    "LLMTimeoutError",
    "LLMResponseFormatError",
    "LLMConnectionError",
    "LLMModelNotFoundError",
    "create_client",
    "get_client",
    # Testing
    "assert_valid_tool_calls",
    "evaluate_transcript",
]
